material:       [basic, extensive]                  # material.f90,        possible values: basic, extensive
constitutive:   [basic, extensive, selective]       # constitutive_*.f90   possible values: basic, extensive, selective
cpfem:          [basic, extensive, selective]       # CPFEM.f90            possible values: basic, extensive, selective

# options for selective debugging
element:          1
integrationpoint: 1
grain:            1

# solver-specific
mesh: [basic]
grid: [basic, rotation, PETSc]
Marc: [basic]
