FreeSurface:
  lattice: cI
  mechanical:
    output: [F, P, F_e, F_p, L_p]
    elastic: {type: Hooke, C_11: 1.e+8, C_12: 1.e+6, C_44: 4.95e+7}
    plastic:
      type: isotropic
      output: [xi]
      xi_0: 0.3e+6
      xi_inf: 0.6e+6
      dot_gamma_0: 0.001
      n: 5
      M: 3
      h_0: 1.e+6
      a: 2
      dilatation: True
