type: Hooke
references:
  - Neighbours, J. R. & Alers, G. A.
    Phys. Rev., American Physical Society, 1958, 111, 707-712
    https://journals.aps.org/pr/abstract/10.1103/PhysRev.111.707
  - Chang, Y. A. & Himmel, L.
    Journal of Applied Physics, American Institute of Physics, 1966, 37, 3567-3572
    https://aip.scitation.org/doi/10.1063/1.1708903
T_ref: 300
C_11: 122.9e+9
C_11, T: -313.5e+5
C_11, T^2: -107.3e+2
C_12: 915.5e+8
C_12, T: -164.1e+5
C_12, T^2: -681.6e+1
C_44: 426.3e+8
C_44, T: -180.5e+5
C_44, T^2: -353.8e+1
