type: phenopowerlaw
references:
- K.M. Jackson and C. Lang,
  Platinum Metals Review 50:15-19, 2006,
  https://doi.org/10.1595/147106705X93359,
  fitted from Fig. 5 (Pt-5% Cu recrystallised)

N_sl: [12]

n_sl: 1.6
a_sl: 0.8
h_0_sl-sl: 300.0e+6
xi_0_sl: [150.0e+6]
xi_inf_sl: [500.0e+6]
h_sl-sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
dot_gamma_0_sl: 0.0001
